# Generated by Django 4.1.7 on 2023-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MGereja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namagereja', models.CharField(max_length=20)),
                ('alamatgereja', models.CharField(max_length=100)),
                ('telepongereja', models.CharField(max_length=15)),
                ('tanggalberdiri', models.DateField()),
                ('tema', models.CharField(max_length=100)),
                ('ayatemas', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MKhotbah',
            fields=[
                ('id_khotbah', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('isi_khotbah', models.CharField(max_length=225)),
                ('tanggal', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MPendeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namapendeta', models.CharField(max_length=50)),
                ('fotopendeta', models.ImageField(blank=True, null=True, upload_to='static/dist/img')),
                ('visi', models.CharField(max_length=500)),
                ('misi', models.CharField(max_length=1000)),
                ('jadwal', models.CharField(max_length=100)),
            ],
        ),
    ]
