# Generated by Django 4.1.7 on 2023-10-25 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadminLog',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MDokumentasi',
            fields=[
                ('id_dokumentasi', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('foto_dokumentasi', models.ImageField(upload_to='static/dist/img')),
                ('nama_kegiatan', models.CharField(max_length=100)),
                ('tanggal_kegiatan', models.DateField()),
                ('keterangan_kegiatan', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MJemaat',
            fields=[
                ('kode_jemaat', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_jemaat', models.CharField(max_length=50)),
                ('status_dalam_keluarga', models.CharField(max_length=50)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(max_length=50)),
                ('status_baptis', models.CharField(max_length=50)),
                ('status_sidi', models.CharField(max_length=50)),
                ('nomor_telepon', models.CharField(max_length=20)),
                ('pendidikan', models.CharField(max_length=50)),
                ('pekerjaan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MJenisibadah',
            fields=[
                ('kode_jenis_ibadah', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_jenis_ibadah', models.CharField(max_length=50)),
                ('periode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MKategorial',
            fields=[
                ('kodekategorial', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('namakategorial', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MKeluarga',
            fields=[
                ('kode_keluarga', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('nama_kepala_keluarga', models.CharField(max_length=50)),
                ('alamat_keluarga', models.CharField(max_length=100)),
                ('jumlah_anggota_keluarga', models.IntegerField()),
                ('foto_keluarga', models.ImageField(upload_to='static/dist/img')),
            ],
        ),
        migrations.CreateModel(
            name='MOrjem',
            fields=[
                ('kode_org_jemaat', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('jabatan_org_jemaat', models.CharField(max_length=50)),
                ('nomor_urut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MOrkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan_kategorial', models.CharField(max_length=50)),
                ('nomor_urut', models.CharField(max_length=50)),
                ('kodekategorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mkategorial')),
            ],
        ),
        migrations.CreateModel(
            name='MRenungan',
            fields=[
                ('id_renungan', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('judul_renungan', models.CharField(blank=True, max_length=225)),
                ('ayat_renungan', models.CharField(blank=True, max_length=225)),
                ('isi_renungan', models.CharField(max_length=1000)),
                ('tanggal_renungan', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MWarta',
            fields=[
                ('id_warta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('judul_warta', models.CharField(blank=True, max_length=225)),
                ('isi_warta', models.CharField(max_length=1000)),
                ('tanggal_warta', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='mgereja',
            name='emailgereja',
            field=models.EmailField(blank=True, max_length=225, unique=True),
        ),
        migrations.AddField(
            model_name='mgereja',
            name='isi_ayatemas',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mkhotbah',
            name='ayat_khotbah',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='mkhotbah',
            name='judul_khotbah',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='mpendeta',
            name='email_pendeta',
            field=models.EmailField(blank=True, max_length=225, unique=True),
        ),
        migrations.AddField(
            model_name='mpendeta',
            name='pendidikan_pendeta',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='mpendeta',
            name='tlpn_pendeta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='mgereja',
            name='ayatemas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mkhotbah',
            name='id_khotbah',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mkhotbah',
            name='isi_khotbah',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mpendeta',
            name='fotopendeta',
            field=models.ImageField(null=True, upload_to='static/dist/img'),
        ),
        migrations.CreateModel(
            name='MPengkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50)),
                ('jabatan_kategorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.morkat')),
                ('kode_jemaat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjemaat')),
                ('kodekategorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mkategorial')),
            ],
        ),
        migrations.CreateModel(
            name='MPengjem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50)),
                ('kemajelisan', models.CharField(max_length=50)),
                ('kode_jemaat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjemaat')),
                ('kode_org_jemaat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.morjem')),
            ],
        ),
        migrations.CreateModel(
            name='MJnstgsibd',
            fields=[
                ('kode_jenis_tugas_ibadah', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nomor_urut', models.CharField(max_length=50)),
                ('jenis_tugas_ibadah', models.CharField(max_length=50)),
                ('kode_jenis_ibadah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjenisibadah')),
            ],
        ),
        migrations.AddField(
            model_name='mjemaat',
            name='kode_keluarga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mkeluarga'),
        ),
        migrations.AddField(
            model_name='mjemaat',
            name='kodekategorial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mkategorial'),
        ),
        migrations.CreateModel(
            name='MJdwlibadah',
            fields=[
                ('id_ibadah', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_ibadah', models.DateTimeField()),
                ('jam_ibadah', models.CharField(max_length=50)),
                ('persembahan', models.CharField(max_length=50)),
                ('kode_jenis_ibadah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjenisibadah')),
            ],
        ),
    ]
