# Generated by Django 4.1.7 on 2023-09-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MWarta',
            fields=[
                ('id_warta', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('isi_warta', models.CharField(max_length=1000)),
                ('tanggal_warta', models.DateField()),
            ],
        ),
    ]
