# Generated by Django 4.1.7 on 2023-10-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_madminlog_mdokumentasi_mjemaat_mjenisibadah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPtgsibadah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_urut', models.CharField(max_length=50)),
                ('id_ibadah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjdwlibadah')),
                ('kode_jemaat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjemaat')),
                ('kode_jenis_tugas_ibadah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjnstgsibd')),
            ],
        ),
    ]
