# Generated by Django 4.1.7 on 2023-09-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mwarta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRenungan',
            fields=[
                ('id_renungan', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('isi_renungan', models.CharField(max_length=500)),
                ('tanggal_renungan', models.DateField()),
            ],
        ),
    ]
