# Generated by Django 4.1.7 on 2023-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mrenungan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDokumentasi',
            fields=[
                ('id_dokumentasi', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('foto_dokumentasi', models.ImageField(blank=True, null=True, upload_to='static/dist/img')),
                ('nama_kegiatan', models.CharField(max_length=100)),
                ('tanggal_kegiatan', models.DateField()),
                ('keterangan_kegiatan', models.CharField(max_length=500)),
            ],
        ),
    ]
