# Generated by Django 4.1.7 on 2023-10-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mptgsibadah'),
    ]

    operations = [
        migrations.CreateModel(
            name='MJnskolekte',
            fields=[
                ('kode_jenis_persembahan', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama_jenis_persembahan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MKolekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_persembahan', models.CharField(max_length=50)),
                ('id_ibadah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjdwlibadah')),
                ('kode_jenis_persembahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjnskolekte')),
            ],
        ),
    ]
