# Generated by Django 4.1.7 on 2023-10-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mjnskolekte_mkolekt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MKolekt',
            new_name='MKolekte',
        ),
    ]
