# Generated by Django 4.1.7 on 2023-09-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mdokumentasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadminLog',
            fields=[
                ('id_admin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
