# Generated by Django 4.1.7 on 2023-11-06 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_mkolekt_mkolekte'),
    ]

    operations = [
        migrations.CreateModel(
            name='MHadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_kehadiran', models.CharField(max_length=50)),
                ('id_ibadah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mjdwlibadah')),
                ('kodekategorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mkategorial')),
            ],
        ),
    ]
