# Generated by Django 4.1.7 on 2023-09-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_madminlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madminlog',
            name='id_admin',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
