# Generated by Django 4.1.7 on 2023-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_mhadir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpendeta',
            name='fotopendeta',
            field=models.ImageField(null=True, upload_to='static/assets/img'),
        ),
    ]
