# Generated by Django 4.1.7 on 2023-09-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_madminlog_id_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mkhotbah',
            name='ayat_khotbah',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='mkhotbah',
            name='judul_khotbah',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='mpendeta',
            name='email_pendeta',
            field=models.EmailField(blank=True, max_length=225, unique=True),
        ),
        migrations.AddField(
            model_name='mpendeta',
            name='pendidikan_pendeta',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='mpendeta',
            name='tlpn_pendeta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mrenungan',
            name='ayat_renungan',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='mrenungan',
            name='judul_renungan',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='mwarta',
            name='judul_warta',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
