# Generated by Django 4.1.7 on 2023-09-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mkhotbah_ayat_khotbah_mkhotbah_judul_khotbah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgereja',
            name='emailgereja',
            field=models.EmailField(blank=True, max_length=225, unique=True),
        ),
        migrations.AddField(
            model_name='mgereja',
            name='isi_ayatemas',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mgereja',
            name='ayatemas',
            field=models.CharField(max_length=50),
        ),
    ]
