# Generated by Django 4.1.7 on 2023-11-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mpendeta_fotopendeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpendeta',
            name='fotopendeta',
            field=models.ImageField(null=True, upload_to='static/dist/img'),
        ),
    ]
