# Generated by Django 4.1.7 on 2023-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_mpendeta_fotopendeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpendeta',
            name='fotopendeta',
            field=models.ImageField(blank=True, null=True, upload_to='static/dist/img'),
        ),
    ]
