# Generated by Django 4.1.7 on 2023-09-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_mgereja_emailgereja_mgereja_isi_ayatemas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkhotbah',
            name='isi_khotbah',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mrenungan',
            name='isi_renungan',
            field=models.CharField(max_length=1000),
        ),
    ]
