# Generated by Django 4.1.7 on 2023-11-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_mpendeta_fotopendeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mkeluarga',
            name='kode_keluarga',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
