# Generated by Django 4.1.7 on 2023-11-17 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_mkeluarga_kode_keluarga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mjdwlibadah',
            name='persembahan',
        ),
    ]
